OPENAI_API_KEY = "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"

[connections.snowpark]
user = "bxy12"
password = "Yu$b1ngb1ng"
warehouse = "HOL_WH"
role = "ACCOUNTADMIN"
# Find your account info here:
# https://docs.snowflake.com/en/user-guide/admin-account-identifier
account = "ksfzsua-bmb51807"
